### ISSUE TITLE
1.5.5 Fails to Start on Servers - ServerProxy class was removed in this version

### ISSUE THREAD

**Issue by TigerWalts** [CaliforniaDemise/VoidIslandControl#1]
```
net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: com.bartz24.voidislandcontrol.proxy.ServerProxy
    at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:102)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
```

Even though the class did nothing Forge is still expecting the class to be there as it is referenced in the mod's main class.

https://github.com/CaliforniaDemise/VoidIslandControl/blob/51e3102b4d9027ebb5fda83dc3b4282df32599ca/src/main/java/com/bartz24/voidislandcontrol/VoidIslandControl.java#L22

As a workaround copying the `ServerProxy.class` file from the 1.5.4 JAR into the 1.5.5 JAR allows the server to start.

**Comment by CaliforniaDemise** [comment]
Fixed
